"""Add concept and attachment to tasks

Revision ID: 1c1b742c2c89
Revises: 015678b10875
Create Date: 2026-06-22 12:57:46.220718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1b742c2c89'
down_revision: Union[str, None] = '015678b10875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('concept', sa.String(length=180), nullable=True))
    op.add_column('tasks', sa.Column('attachment_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'attachment_data')
    op.drop_column('tasks', 'concept')
    # ### end Alembic commands ###
